app:
    chethiya:
        couchbase:
            bucketname: application-bucket
            connection:
                string: couchbase://host
            password: 1s@secret
            username: app_user
eureka:
    client:
        serviceUrl:
            defaultZone: http://host:8761/eureka
resilience4j:
    retry:
        instances:
            get-applicant:
                enableExponentialBackOff: true
                maxAttempts: 3
server:
    port: 8580
spring:
    application:
        name: application-service
    cloud:
        config:
            server:
                enabled: true
