spring.application.name=application-service

app.chethiya.couchbase.connection.string=couchbase://127.0.0.1
app.chethiya.couchbase.username=app_user
app.chethiya.couchbase.password=1s@secret
app.chethiya.couchbase.bucketname=application-bucket

server.port=8580

spring.cloud.config.server.enabled=false

app.chethiya.applicant-service.uri=http://localhost:8380/
app.chethiya.position-service.uri=http://localhost:8280/

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
