eureka:
    client:
        serviceUrl:
            defaultZone: http://naming-server:8761/eureka
    instance:
        preferIpAddress: true
server:
    port: 8280
spring:
    application:
        name: position-service
    datasource:
        password: 1s@secret
        url: jdbc:postgresql://postgres:5432/application-service
        username: position_user
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                default_schema: position_service
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
management:
    tracing:
        sampling:
            probability: 1.0
logging:
    pattern:
        level: "[%5p [${spring.application.name}-#-%X{traceId}-#-%X{spanId}]]"
